"""Generate paper/data/numbers.tex from paper/data/metrics.json.

Converts canonical SSOT metrics into LaTeX \\newcommand macros that can be
\input{data/numbers.tex} in main.tex and referenced in the paper.

Usage:
    python scripts/generate_paper_numbers.py [--dry-run]
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
METRICS = ROOT / "paper" / "data" / "metrics.json"
OUT = ROOT / "paper" / "data" / "numbers.tex"

# ── formatting helpers ─────────────────────────────────────────────────────

def fmt_r(v: float, decimals: int = 3) -> str:
    """Format a Pearson r value with leading zero: 0.631"""
    return f"{v:.{decimals}f}"


def fmt_delta(v: float) -> str:
    """Format a delta value with explicit sign: +0.003"""
    return f"{v:+.3f}"


def fmt_plain(v: float, decimals: int = 3) -> str:
    return f"{v:.{decimals}f}"


# ── macro definitions ──────────────────────────────────────────────────────
# Each entry: (macro_name, value_key, formatter_fn, comment)
MACROS = [
    # Drug feature null
    ("RidgeNoDrugR",     "ridgeNoDrugPerDrugR",     fmt_r,   "Ridge no-drug per-drug Pearson r"),
    ("RidgeMorganDelta", "ridgeMorganDeltaPerDrugR", fmt_delta, "Ridge Morgan FP - no-drug delta"),
    # LINCS
    ("LincsGlobalR",     "lincsGlobalR",             fmt_r,   "LINCS signatures global r"),
    ("LincsBaseline",    "morganBaselineGlobalR",     fmt_r,   "Morgan FP global r (LINCS baseline)"),
    ("LincsLift",        "lincsGlobalRLift",          fmt_delta, "LINCS global r lift vs Morgan FP"),
    # Response matching
    ("CellMeanR",        "cellMeanPriorPerDrugR",     fmt_r,   "Cell-mean prior per-drug r (K=0)"),
    ("KFiftyR",          "kFiftyBlendedPerDrugR",     fmt_r,   "Response matching K=50 blended per-drug r"),
    ("KFiftyLift",       "kFiftyLiftVsCellMean",      fmt_delta, "K=50 lift vs cell-mean prior"),
    # MoA stratified
    ("ErkMapkAllDrug",   "erkMapkAllDrugPerDrugR",    fmt_r,   "ERK MAPK all-drug per-drug r"),
    ("ErkMapkMoaR",      "erkMapkMoaStratifiedPerDrugR", fmt_r, "ERK MAPK MoA-stratified per-drug r"),
    ("ErkMapkMoaStd",    "erkMapkMoaStratifiedStd",   lambda v: f"{v:.3f}", "ERK MAPK std across seeds"),
    ("EgfrAllDrug",      "egfrAllDrugPerDrugR",       fmt_r,   "EGFR all-drug per-drug r"),
    ("EgfrMoaR",         "egfrMoaStratifiedPerDrugR", fmt_r,   "EGFR MoA-stratified per-drug r"),
    # BeatAML
    ("BeatAmlNoDrugR",   "beatAmlNoDrugPerDrugR",     fmt_r,   "BeatAML no-drug per-drug r"),
    ("BeatAmlKFiftyR",   "beatAmlKFiftyPerDrugR",     fmt_r,   "BeatAML K=50 per-drug r"),
    ("BeatAmlKFiftyLift","beatAmlKFiftyLift",          fmt_delta, "BeatAML K=50 lift"),
    # PASO
    ("PasoFairMean",     "pasoFairMean",              fmt_r,   "PASO fair 10-fold mean"),
    ("PasoInflation",    "pasoInflation",             fmt_delta, "PASO test-set snooping inflation"),
    ("PasoBestFold",     "pasoBestFoldTestR",         fmt_r,   "PASO best-fold test r"),
]


# ── main ───────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not METRICS.exists():
        print(f"ERROR: {METRICS} not found. Run extract_ssot.py first.")
        return

    with open(METRICS) as f:
        m = json.load(f)

    lines = [
        "% Auto-generated by scripts/generate_paper_numbers.py — do not edit.",
        "% Source: paper/data/metrics.json",
        "% Run: python scripts/extract_ssot.py && python scripts/generate_paper_numbers.py",
        "%",
    ]

    for macro, key, fmt_fn, comment in MACROS:
        if key not in m:
            lines.append(f"% MISSING: \\{macro} ({key} not in metrics)")
            continue
        val = fmt_fn(m[key])
        lines.append(f"\\newcommand{{\\{macro}}}{{{val}}}% {comment}")

    tex = "\n".join(lines) + "\n"

    if args.dry_run:
        print(tex)
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write(tex)
    print(f"Wrote {OUT} ({len(MACROS)} macros)")


if __name__ == "__main__":
    main()
